### ISSUE TITLE
disabling WebP texture compression

### ISSUE THREAD

**Issue by AhmadMansy** [juunini/gltf-optimizer#2]
Is there a way to disable WebP compression when using the cli tool?

**Comment by juunini** [comment]
Sorry, this library is working node v16
https://github.com/GoogleChromeLabs/squoosh/issues/1260#issuecomment-1369809452
I'll change squoosh to other.

And, fixed web optimizer. now working.

**Comment by juunini** [comment]
This issue completed in https://github.com/juunini/gltf-optimizer/pull/3
